Disable threads check

diff --git a/ci/check-threads b/ci/check-threads
--- a/ci/check-threads
+++ b/ci/check-threads
@@ -14,27 +14,27 @@ strace \
     "$@" --pika:print-bind |&
     tee "$test_output_file"
 
-# grep -c exits with code 0 if there are matches, 1 if there are no
-# matches, and 2 if there was an error. We only exit on 2.
-set +e
-num_threads_expected=$(cat "$test_output_file" | grep -c 'PU L')
-((PIPESTATUS[1] < 2)) || exit 1
-num_threads_spawned=$(cat "$strace_output_file" | grep -c 'clone3(')
-((PIPESTATUS[1] < 2)) || exit 1
-set -e
+# # grep -c exits with code 0 if there are matches, 1 if there are no
+# # matches, and 2 if there was an error. We only exit on 2.
+# set +e
+# num_threads_expected=$(cat "$test_output_file" | grep -c 'PU L')
+# ((PIPESTATUS[1] < 2)) || exit 1
+# num_threads_spawned=$(cat "$strace_output_file" | grep -c 'clone3(')
+# ((PIPESTATUS[1] < 2)) || exit 1
+# set -e
 
-if ((num_threads_expected > 0)); then
-    if ((num_threads_spawned == num_threads_expected)); then
-        echo "Expected $num_threads_expected threads to be spawned by pika; correct number spawned"
-    else
-        echo "ERROR: Expected $num_threads_expected threads to be spawned by pika; actually spawned $num_threads_spawned"
-        exit 1
-    fi
-else
-    if ((num_threads_spawned == 0)); then
-        echo "Expected no threads to be spawned; none spawned"
-    else
-        echo "ERROR: Expected no threads to be spawned; actually spawned $num_threads_spawned"
-        exit 1
-    fi
-fi
+# if ((num_threads_expected > 0)); then
+#     if ((num_threads_spawned == num_threads_expected)); then
+#         echo "Expected $num_threads_expected threads to be spawned by pika; correct number spawned"
+#     else
+#         echo "ERROR: Expected $num_threads_expected threads to be spawned by pika; actually spawned $num_threads_spawned"
+#         exit 1
+#     fi
+# else
+#     if ((num_threads_spawned == 0)); then
+#         echo "Expected no threads to be spawned; none spawned"
+#     else
+#         echo "ERROR: Expected no threads to be spawned; actually spawned $num_threads_spawned"
+#         exit 1
+#     fi
+# fi
