add pragma once check + always run check format for script

diff --git a/.github/workflows/check_format.yml b/.github/workflows/check_format.yml
--- a/.github/workflows/check_format.yml
+++ b/.github/workflows/check_format.yml
@@ -8,12 +8,13 @@ jobs:
     runs-on: ubuntu-18.04
 
     steps:
+      - uses: actions/checkout@v2
+      - uses: actions/javascript-action@v1
+
       - name: Install tools
         run: |
           sudo apt-get install --no-install-recommends clang-format-10 python3
           pip3 install black==21.8b0
-      - name: Checkout
-        uses: actions/checkout@v2
       - name: Checkout master
         run: git fetch --no-tags --depth=1 origin +refs/heads/master:refs/heads/master
 
@@ -22,9 +23,24 @@ jobs:
         run: ./.github/format.sh
 
       - name: Check scripts formatting
+        if: always()
         run: black --line-length 105 scripts/
 
          # Fails if there are differences.
       - name: Formatting issues
         if: always()
         run: git diff --color --exit-code
+
+      - name: Check include guards
+        if: always()
+        run: |
+          find include test -type f '(' -name "*.h" -o -name "*.h.in" ')'             \
+            | xargs -I{} sh -c                                                        \
+                "egrep -sq '^#pragma once' {} || echo {}"                             \
+            > pragma-once.check
+
+          for filepath in `cat pragma-once.check`; do                                 \
+            echo "::error file=$filepath,line=1::missing include guard in $filepath"; \
+          done
+
+          test ! -s pragma-once.check
